apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sequence-dev

resources:
  - ../../base/auth-service
  - ../../base/game-service
  - ../../base/matchmaking-service
  - ../../base/leaderboard-service
  - ../../base/notification-service
  - ../../base/analytics-service
  - namespace.yaml

images:
  - name: acrsequenceprod.azurecr.io/auth-service
    newTag: "dev"
  - name: acrsequenceprod.azurecr.io/game-service
    newTag: "dev"
  - name: acrsequenceprod.azurecr.io/matchmaking-service
    newTag: "dev"
  - name: acrsequenceprod.azurecr.io/leaderboard-service
    newTag: "dev"
  - name: acrsequenceprod.azurecr.io/notification-service
    newTag: "dev"
  - name: acrsequenceprod.azurecr.io/analytics-service
    newTag: "dev"

patches:
  # Scale down to 1 replica in dev to save cost
  - patch: |
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
