apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: analytics-service-prod
  namespace: argocd
  labels:
    environment: prod
    service: analytics-service
spec:
  project: sequence-prod
  source:
    repoURL: https://github.com/Callmeanurag/Sequence.git
    targetRevision: HEAD
    path: kubernetes/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: sequence-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 5
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
